### ISSUE TITLE
Broken example

### ISSUE THREAD

**Issue by MichaelJCole** [wmfs/cardscript#98]
Hi, cool project, thanks for putting it together.

I noticed the "Basic Problem" example looked broken:
https://wmfs.github.io/cardscript/

With the message: instance does not match allOf schema <#/definitions/AdaptiveCard> with 1 error[s]:

**Comment by reecebrend** [comment]
Hey Michael,

The "basic problem" example was created to illustrate error handling and get easy access to error messages within the cardscript playpen. Since the final element of the body array is just a set of empty brackets and this is not valid cardscript JSON, we throw the error.

Hope this clears things up :)
